sudo yum -y install wget;
sudo wget dl.fedoraproject.org/pub/epel/7/x86_64/Packages/e/epel-release-7-11.noarch.rpm;
sudo rpm -ihv epel-release-7-11.noarch.rpm;
sudo rm -rf epel-release-7-11.noarch.rpm;
sudo yum -q update;
sudo yum -y -q install htop git;
sudo yum -y upgrade;
sudo yum -q clean all;
sudo rm -rf /var/cache/yum;
sudo yum -y install yum-utils device-mapper-persistent-data lvm2;
echo Adding Docker Repo;
sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo;
sudo yum update;
echo Installing Docker;
sudo yum -y install docker-ce;
echo Installed Docker;
echo Starting Docker;
sudo systemctl start docker;
echo Started Docker;
echo Cleaning Cache;
sudo yum clean all;
sudo rm -rf /var/cache/yum;
echo Cleaned Cache;
git clone https://github.com/pwentrys/app_factory.git;
cd app_factory;
echo Starting Docker Build;
sudo docker build -t flask:latest .;
echo Finished Docker Build;
echo Starting Docker Container;
sudo docker run -d -p 80:80 flask;
echo Started Docker Container;
echo Finished All Tasks;
exit;
sudo rm -rf run.sh;