# -*- mode: ruby -*-
# vi: set ft=ruby :

# Force UTF-8
ENV["LC_ALL"] = "en_US.UTF-8"

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # Official CentOS 7.4 Image
  config.vm.box = "CentosBox/Centos-7-v7.4-Minimal-CLI"
  config.vm.box_version = "17.11.24"

  # Fixes error when booting from this as base image.
  config.ssh.insert_key = false

  # Auto-set hostname
  config.vm.hostname = "centos74"
  
  # Set static IP for now.
  # config.vm.network "public_network", ip: "192.168.0.250"
  config.vm.provider "virtualbox" do |vb|
  	vb.cpus = 4
  	vb.memory = 4096

  	vb.name =  "centos74"
  	vb.gui = false
  end

  # Run updates
  config.vm.provision "shell", 
    inline: <<-SHELL
      yum install -y -q wget
      wget dl.fedoraproject.org/pub/epel/7/x86_64/Packages/e/epel-release-7-11.noarch.rpm
      rpm -ihv epel-release-7-11.noarch.rpm
      rm -rf epel-release-7-11.noarch.rpm
      yum update -q
      yum install -y -q htop
      yum upgrade -y -q
      yum clean all
      rm -rf /var/cache/yum
  SHELL
end
